In [32]:
#Step 1: Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [34]:
#Step 2: Importing the dataset
dataset = pd.read_csv('dataset.csv')

In [36]:
#Step 3:Describe dataset,See dimention and Exlpore dataset
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.863333     3.002000      3.706667     1.226667
std        0.829038     0.585103      1.831809     0.735820
min        4.300000     2.000000      1.000000     0.100000
25%        5.300000     2.600000      1.600000     0.425000
50%        5.700000     2.900000      4.000000     1.400000
75%        6.500000     3.400000      5.150000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [38]:

dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.2          0.1  Iris-setosa
1           4.9          3.0           1.2          0.6  Iris-setosa
2           5.6          2.6           1.3          0.3  Iris-setosa
3           4.6          4.1           1.1          0.1  Iris-setosa
4           5.4          3.6           1.8          0.1  Iris-setosa

In [40]:
dataset.shape

(150, 5)

In [42]:

X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.2, 0.1],
       [4.9, 3. , 1.2, 0.6],
       [5.6, 2.6, 1.3, 0.3],
       [4.6, 4.1, 1.1, 0.1],
       [5.4, 3.6, 1.8, 0.1],
       [5.5, 3.5, 1.6, 0.1],
       [4.4, 3. , 1.6, 0.2],
       [4.8, 3.3, 1.1, 0.2],
       [4.9, 4.3, 1.4, 0.6],
       [5.6, 3.6, 1.6, 0.5],
       [4.6, 2.6, 1.5, 0.3],
       [5.6, 4.4, 1.2, 0.1],
       [4.5, 4.3, 1. , 0.5],
       [5.6, 4.4, 1.3, 0.3],
       [4.9, 3.4, 1.7, 0.1],
       [4.7, 2.9, 1.5, 0.5],
       [5.4, 3.1, 1.6, 0.3],
       [4.5, 3.8, 1.8, 0.3],
       [5.8, 4.2, 1.3, 0.2],
       [4.5, 3.4, 1.6, 0.5],
       [4.8, 2.4, 1.6, 0.2],
       [5.5, 2.4, 1. , 0.4],
       [5.4, 3.2, 1.2, 0.4],
       [4.7, 2.9, 1.5, 0.6],
       [5.5, 3. , 1.6, 0.1],
       [4.9, 3.7, 1.7, 0.4],
       [5.7, 3.8, 1.8, 0.2],
       [5.2, 3.4, 1.6, 0.6],
       [5.4, 3.1, 1.3, 0.3],
       [5.8, 4.2, 1.6, 0.3],
       [5.4, 2.6, 1.3, 0.4],
       [5.3, 2.4, 1.9, 0.2],
       [4.3, 4.4, 1.2, 0.3],
       [5. , 3.2, 1.5, 0.1],
       [5.2, 2

In [44]:
y = dataset['species'].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [46]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [48]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.20092514,  0.87851025,  1.63673966,  0.79952933],
       [-0.20092514, -0.80822943,  0.8398418 ,  0.66305206],
       [ 1.05604728, -1.14557736,  1.15860095,  0.9360066 ],
       [ 0.37042596, -0.47088149, -0.16956216, -0.29228882],
       [-1.80070822,  2.39657596, -1.33834569, -1.24762969],
       [ 2.08447927, -0.13353356,  1.31798052,  1.3454384 ],
       [ 0.82750684, -1.14557736, -0.01018258,  0.66305206],
       [-0.5437358 ,  0.37248835, -1.33834569, -1.11115242],
       [-0.77227624, -0.9769034 , -0.2758152 ,  0.52657479],
       [-1.22935712, -0.9769034 , -1.12583959, -1.38410696],
       [-0.20092514, -0.63955546, -1.28521916, -1.11115242],
       [ 2.19874949,  0.70983628,  1.58361314,  0.52657479],
       [-0.20092514,  1.21585818, -1.01958654, -1.52058423],
       [-0.08665492,  2.05922802, -1.28521916, -1.38410696],
       [ 0.37042596,  0.54116231,  0.52108266,  0.52657479],
       [-1.34362734, -0.13353356, -1.17896611, -0.97467515],
       [-1.57216778,  0.

In [50]:
X_test


array([[ 0.0276153 , -0.13353356, -0.2758152 ,  0.25362026],
       [-0.31519536,  2.39657596, -1.28521916, -1.24762969],
       [ 0.14188552, -0.63955546,  0.68046223, -0.01933428],
       [-0.5437358 ,  0.03514041, -1.17896611, -0.97467515],
       [-1.1150869 ,  1.21585818, -1.07271306, -1.11115242],
       [-1.00081668,  1.89055405, -1.01958654, -1.38410696],
       [-0.88654646, -0.63955546,  0.36170308,  0.39009752],
       [-0.5437358 , -0.63955546, -1.28521916, -1.11115242],
       [ 1.05604728, -0.30220753,  1.0523479 ,  0.52657479],
       [ 1.17031751, -0.13353356,  0.14919699,  0.25362026],
       [-1.00081668,  0.37248835, -1.17896611, -1.52058423],
       [-0.42946558,  0.87851025, -1.12583959, -1.52058423],
       [ 0.48469618, -0.47088149, -0.2758152 ,  0.39009752],
       [ 0.37042596,  0.20381438,  0.8398418 ,  1.20896113],
       [ 0.71323662, -0.47088149,  0.52108266,  1.61839293],
       [-0.20092514, -1.31425133, -0.11643563,  0.52657479],
       [-0.20092514,  0.

In [52]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [54]:
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [56]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 9,  0,  0],
       [ 0, 11,  0],
       [ 0,  1,  9]], dtype=int64)

In [58]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
Accuracy :  1.0

Accuracy :  0.9666666666666667


In [60]:
#Step 8: Comparing the Real Values with Predicted Values


df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2   Iris-versicolor  Iris-versicolor
3       Iris-setosa      Iris-setosa
4       Iris-setosa      Iris-setosa
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12  Iris-versicolor  Iris-versicolor
13   Iris-virginica   Iris-virginica
14   Iris-virginica   Iris-virginica
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica  Iris-versicolor
17  Iris-versicolor  Iris-versicolor
18  Iris-versicolor  Iris-versicolor
19  Iris-versicolor  Iris-versicolor
20   Iris-virginica   Iris-virginica
21      Iris-setosa      Iris-setosa
22  Iris-versicolor  Iris-versicolor
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25      Iris-setosa      Iris-setosa
26  Iris-versicolor  Iris-versicolor
27   Iris-virginica   Iris-virginica
28   Iris-virginica   Iris-virginica
29   Iris-virginica   Iris-virginica